// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBd9DNEAlxHPNNqQUM5OLVcuyDSd0OB6vc',
    appId: '1:464377529968:web:6c17c704b2f86412e556b5',
    messagingSenderId: '464377529968',
    projectId: 'academic-dashboard-app-rghqhf',
    authDomain: 'academic-dashboard-app-rghqhf.firebaseapp.com',
    storageBucket: 'academic-dashboard-app-rghqhf.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQ8DDAQhYvG_gq3fM4x01RNwDEZkzVTv4',
    appId: '1:464377529968:android:1097491e85964039e556b5',
    messagingSenderId: '464377529968',
    projectId: 'academic-dashboard-app-rghqhf',
    storageBucket: 'academic-dashboard-app-rghqhf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-io7FYEWkMBMiAMv-HI0pQzip2gAePnk',
    appId: '1:464377529968:ios:932b63b9147f6198e556b5',
    messagingSenderId: '464377529968',
    projectId: 'academic-dashboard-app-rghqhf',
    storageBucket: 'academic-dashboard-app-rghqhf.firebasestorage.app',
    iosBundleId: 'com.example.academicDashboardApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD-io7FYEWkMBMiAMv-HI0pQzip2gAePnk',
    appId: '1:464377529968:ios:932b63b9147f6198e556b5',
    messagingSenderId: '464377529968',
    projectId: 'academic-dashboard-app-rghqhf',
    storageBucket: 'academic-dashboard-app-rghqhf.firebasestorage.app',
    iosBundleId: 'com.example.academicDashboardApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBd9DNEAlxHPNNqQUM5OLVcuyDSd0OB6vc',
    appId: '1:464377529968:web:9f48510c999e1254e556b5',
    messagingSenderId: '464377529968',
    projectId: 'academic-dashboard-app-rghqhf',
    authDomain: 'academic-dashboard-app-rghqhf.firebaseapp.com',
    storageBucket: 'academic-dashboard-app-rghqhf.firebasestorage.app',
  );
}
